# Generated by Django 2.2.5 on 2020-06-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200605_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('expire_time', models.IntegerField(blank=True, help_text='有效期按天数计算', null=True, verbose_name='有效期')),
                ('expire_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='提示文本')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='课程价格')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_expire', to='course.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程有效期',
                'verbose_name_plural': '课程有效期',
                'db_table': 'ly_course_expire',
            },
        ),
    ]
