# Generated by Django 2.2.5 on 2020-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果价格为0，那么该课程没有永久有效的选项', max_digits=6, verbose_name='课程原价'),
        ),
    ]
