# Generated by Django 2.2.5 on 2020-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
