# Generated by Django 3.2.25 on 2024-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果填写的价格为0，那么表示当前课程在购买的时候，没有永久有效的期限。', max_digits=6, verbose_name='课程原价'),
        ),
    ]
