# Generated by Django 3.2.25 on 2024-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscount',
            name='sale',
            field=models.TextField(blank=True, help_text='\n    优惠公式：\n    不填表示免费；<br>\n    *号开头表示折扣价，例如*0.82表示八二折；<br>\n    -号开头则表示减免，例如-20表示原价-20；<br>\n    如果需要表示满减,则需要使用 原价-优惠价格,例如表示课程价格大于100,优惠10;大于200,优惠25,格式如下:<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满100-10<br>\n    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;满200-25<br>\n    ', null=True, verbose_name='优惠公式'),
        ),
    ]
